### ISSUE TITLE
Remove hardcoded paths

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-fuel-tools#1]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-fuel-tools/issues/1)) by Andrés Fortier (Bitbucket: [andres_fortier](https://bitbucket.org/%7Bf9c4496c-9146-4675-b1d5-bd0ed156cf58%7D/)).**

----------------------------------------
After successfully installing ign-tools and ign-fuel-tools I'm seeing the following:

```
$ ign
The 'ign' command provides a command line interface to the ignition tools.

  ign <command> [options]

List of available commands:

  help:          Print this help text.
  fuel:          Manage simulation resources.

Options:

  --force-version <VERSION>  Use a specific library version.
  --versions                 Show the available versions.
Use 'ign help <command>' to print help for a command.
$ ign help fuel
Unable to find configuration file in [/home/caguero/.ignition/fuel/.sources.yaml]
```

**Comment by chapulina** [comment]
I believe this has been fixed.
