### ISSUE TITLE
Downloads fail on Windows due to https support in libcurl

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-fuel-tools#105]
Our download tests are failing on Jenkins (Windows) with this message:

`libcurl: (1) Protocol "https" not supported or disabled in libcurl`

I didn't dig too deep and will open a PR disabling the tests for now.

**Comment by ahcorde** [comment]
This was fixed with this two PRs
 - https://github.com/ignition-tooling/release-tools/pull/434
 - https://github.com/ignition-tooling/release-tools/pull/430
