### ISSUE TITLE
Missing .mtl files for collision meshes in some fuel models

### ISSUE THREAD

**Issue by ojasjoshi** [ignitionrobotics/ign-fuel-tools#118]
```OpScrubs```, ```PatientWheelChair```, ```VisitorChair``` models do not have ```.mtl``` files for their collision meshes. This is resulting in a error message suggesting default materials to be used for these models. 

Is this intended from ignition or are these files missing by error?

**Comment by chapulina** [comment]
I see an `OpScrubs_Col.mtl` here:

https://app.ignitionrobotics.org/OpenRobotics/fuel/models/OpScrubs

Could you be more specific about the error you're seeing and how you are getting the model?

**Comment by chapulina** [comment]
I should also point out that this is probably not the correct place to post this issue. This reository is for the C++ client library and command line tool.

For issues with the contents of models, please refer to the Information link on the left here: https://app.ignitionrobotics.org/dashboard

**Comment by ojasjoshi** [comment]
Correction: ```VisitorChair``` model does not have a .mtl file for the collision mesh.  

Error:
```bash
[Err] [OBJLoader.cc:79] WARN: Material file [fuel_models/VisitorChair/meshes/VisitorChair_Col.mtl ] not found. Created a default material.
[Wrn] [OBJLoader.cc:141] Missing material for shape[VisitorChair_Col_Cube.009] in OBJ file[/home/ANT.AMAZON.COM/ojasjosh/git_repos/aws-robomaker-hospital-world/fuel_models/VisitorChair/meshes/VisitorChair_Col.obj]
```

Sorry about creating the issue here. Would you recommend creating a support ticket [here](https://openrobotics.freshdesk.com/support/home)?

**Comment by ojasjoshi** [comment]
Correction: ```VisitorChair``` model does not have a .mtl file for the collision mesh.  

Error:
```bash
[Err] [OBJLoader.cc:79] WARN: Material file [fuel_models/VisitorChair/meshes/VisitorChair_Col.mtl ] not found. Created a default material.
[Wrn] [OBJLoader.cc:141] Missing material for shape[VisitorChair_Col_Cube.009] in OBJ file[fuel_models/VisitorChair/meshes/VisitorChair_Col.obj]
```

Sorry about creating the issue here. Would you recommend creating a support ticket [here](https://openrobotics.freshdesk.com/support/home)?

**Comment by chapulina** [comment]
> Would you recommend creating a support ticket here?

Yes, I think that's the best place right now.

> Sorry about creating the issue here. 

No worries, I'll close it now :wink:
