### ISSUE TITLE
[Fuel backend] Support uploading a model

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-fuel-tools#12]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-fuel-tools/issues/12)) by Shane Loretz (Bitbucket: [Shane Loretz](https://bitbucket.org/%7B656e3311-aad9-45a1-aaf7-b0ee0e84b287%7D/), GitHub: [sloretz](https://github.com/sloretz)).**

----------------------------------------
The tools do not currently support uploading a model. `FuelClient::UploadModel()` has no implementation. The command line just prints a TODO message.

```
$ ign fuel push --url https://staging-api.ignitionfuel.org/ --owner sloretz --name box --path ~/models/box
TODO Upload a model
```

The thought behind the command line args is a user would want to upload a model which they created and lives in some directory. When they want to upload it they would say which url, who the owner is (their username on the server), what the name of the model is, and where the path to the model on disk is. `FuelClient` should create a zip archive of the model and `POST` it to some api on the fuel server.

**Comment by chapulina** [comment]
`ign fuel upload -m ~/path_to_model --header 'authorization: Bearer <JWT TOKEN>'`
