### ISSUE TITLE
Update dependecies on documentation

### ISSUE THREAD

**Issue by joaobrittoneto** [ignitionrobotics/ign-fuel-tools#127]
While updating from Gazebo9 (that requires ign-fuel-tools1) to Gazebo11 (ign-fuel-tools4), I come up with the follow error:

```
/usr/lib/x86_64-linux-gnu/libignition-fuel_tools4.so.4.2.1: undefined reference to `ignition::msgs::FuelMetadata::default_instance_'
```

As ign-msgs was compiled from source, but not ign-fuel-tools, I got the error. 
I was not aware at first that ign-fuel-tools depends on ign-msgs now. At least I couldn't see it on a quick look to the documentation.

If it's the case, it would be nice to update the dependency list on the docs. Otherwise, sorry to bother.

**Comment by chapulina** [comment]
Thank you for the pointer. It looks like the tutorial already mentions `ign-msgs`:

https://github.com/ignitionrobotics/ign-fuel-tools/blob/ign-fuel-tools4/tutorials/01_installation.md

But the live tutorial seems outdated:

https://ignitionrobotics.org/api/fuel_tools/4.0/install.html

I'll keep this issue open until we deploy the updated tutorial.

**Comment by chapulina** [comment]
The latest tutorial is up-to-date: https://ignitionrobotics.org/api/fuel_tools/4.3/install.html
