### ISSUE TITLE
[Fuel backend] Support downloading a model

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-fuel-tools#13]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-fuel-tools/issues/13)) by Shane Loretz (Bitbucket: [Shane Loretz](https://bitbucket.org/%7B656e3311-aad9-45a1-aaf7-b0ee0e84b287%7D/), GitHub: [sloretz](https://github.com/sloretz)).**

----------------------------------------
`Model::Fetch()` has a mostly empty implementation. It should download a model from the fuel server if that model doesn't already exist on disk. Saving to disk would require implementing `LocalCache::SaveModel` and making sure `Model` has access to the `FuelClient` instance of `LocalCache`.

In order to make it possible to test the library with a mock REST class, `ModelPrivate` must be given an instance of `REST`  and `LocalCache` classes from `FuelClient`, which may be difficult. The instances might have to pass through  `ModelIter` or `LocalCache` when so they can be given to created `Model` instances.

**Comment by chapulina** [comment]
`ign fuel download --url https://fuel.ignitionrobotics.org/1.0/openrobotics/models/Ambulance`
