### ISSUE TITLE
[Fuel backend] Support deleting a model

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-fuel-tools#14]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-fuel-tools/issues/14)) by Shane Loretz (Bitbucket: [Shane Loretz](https://bitbucket.org/%7B656e3311-aad9-45a1-aaf7-b0ee0e84b287%7D/), GitHub: [sloretz](https://github.com/sloretz)).**

----------------------------------------
`FuelClient::DeleteModel()` currently has no implementation. There is no placeholder action on the ruby command line too either. Maybe call it `ign fuel rm` ?

**Comment by chapulina** [comment]
`ign fuel delete -- url --header 'authorization: Bearer <JWT TOKEN>'`
