### ISSUE TITLE
[Fuel backend] Create ClientConfig from yaml file

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-fuel-tools#15]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-fuel-tools/issues/15)) by Shane Loretz (Bitbucket: [Shane Loretz](https://bitbucket.org/%7B656e3311-aad9-45a1-aaf7-b0ee0e84b287%7D/), GitHub: [sloretz](https://github.com/sloretz)).**

The original report had attachments: [sources.yaml](https://osrf-migration.github.io/ignition-gh-pages/data/repositories/ignitionrobotics/ign-fuel-tools/issues/15/attachments/sources.yaml)

----------------------------------------
`ClientConfig` is a class that holds config info about servers - what their URL is, the name of the folder where models from them are saved, auth info etc. Currently the creation of this config is hard coded. The `ign fuel` tool is hardcoded to do requests from `https://staging-api.ignitionfuel.org/` using the local cache directory named `staging_ignitionfuel`.

There should be a method or class which populates an instance `ClientConfig` from a yaml file before it's given to `FuelClient`. This class would be used to populate the config in `IgnitionFuelCMD.cc/getConfig()`.

Attached is a config file from @caguero

**Comment by chapulina** [comment]
https://github.com/ignitionrobotics/ign-fuel-tools/blob/master/src/ClientConfig.cc#L243
