### ISSUE TITLE
New release for ign-fuel-tools4/Citadel? 

### ISSUE THREAD

**Issue by traversaro** [ignitionrobotics/ign-fuel-tools#189]
## Desired behavior
Hi everyone! For Gazebo 11 Windows packaging, it would be nice to make a release of the ign-fuel-tools4 branch, as it includes a critical bug fix for Windows: https://github.com/ignitionrobotics/ign-fuel-tools/pull/178 . The required changes in ignition-common3 (https://github.com/ignitionrobotics/ign-common/pull/197) were already release in 3.13 (see https://github.com/ignitionrobotics/ign-common/tags).

cc @Tobias-Fischer

## Alternatives considered
An alternative we tried in https://github.com/conda-forge/libignition-fuel-tools-feedstock/pull/32#issuecomment-859291664 was to backport the patch to an earlier release, but unfortunately it does not apply cleanly. 

## Implementation suggestion
I guess following the standard release process will be ok.

## Additional context
This came out in https://github.com/conda-forge/libignition-fuel-tools-feedstock/pull/32#issuecomment-859291664 .

**Comment by Tobias-Fischer** [comment]
Seems like this can be closed - thanks @chapulina!

**Comment by traversaro** [comment]
Thanks a lot!
