### ISSUE TITLE
[Fuel backend] ign fuel output isn't pretty

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-fuel-tools#19]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-fuel-tools/issues/19)) by Shane Loretz (Bitbucket: [Shane Loretz](https://bitbucket.org/%7B656e3311-aad9-45a1-aaf7-b0ee0e84b287%7D/), GitHub: [sloretz](https://github.com/sloretz)).**

----------------------------------------
`ign fuel list` lists the output of `Model::UniqueName()`. This isn't very pretty to look at.

**Comment by chapulina** [comment]
The output now defaults to "pretty", with colors, indentation and lines. The "ugly" machine-readable output can be achieved with the `--raw` option.
