### ISSUE TITLE
[Girder backend] Add search-by-tag plugin

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-fuel-tools#2]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-fuel-tools/issues/2)) by Andrés Fortier (Bitbucket: [andres_fortier](https://bitbucket.org/%7Bf9c4496c-9146-4675-b1d5-bd0ed156cf58%7D/)).**

----------------------------------------
Add search-by-tag plugin that provides a new REST endpoint. Tags should be added to the metadata of both folders and items and we should find a way to properly query them (i.e. to make proper use of limit / count parameters)

**Comment by chapulina** [comment]
I believe we're not considering Girder anymore, so closing this.
