### ISSUE TITLE
docs, ui: Possible to provide concrete link back to App? Possible to add `ign fuel` cmd to App?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [ignitionrobotics/ign-fuel-tools#215]
## Desired behavior
With download example here: https://ignitionrobotics.org/libs/fuel_tools

Would be nice to:
- see the original model link from this, e.g. https://app.ignitionrobotics.org/OpenRobotics/fuel/models/Ambulance.
- see an example of downloading a specific version (e.g. model's version 1)

From web UI, it would be nice to see minimal `ign fuel download` command to retrieve model programmatically (incl. version by default?)

## Alternatives considered
N/A

## Implementation suggestion
Doc edit
(hopefully quick?) UI edit

## Additional context
Usage here: https://github.com/EricCousineau-TRI/repro/pull/73

FYI @marcoag @azeey

**Comment by azeey** [comment]
@EricCousineau-TRI, I've opened a ticket on the web app here: https://gitlab.com/ignitionrobotics/web/app/-/issues/15.

**Comment by EricCousineau-TRI** [comment]
Thanks! Closing this in lieu of gitlab issue.
