### ISSUE TITLE
[Fuel backend] ModelIdentifier unit test

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-fuel-tools#22]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-fuel-tools/issues/22)) by Shane Loretz (Bitbucket: [Shane Loretz](https://bitbucket.org/%7B656e3311-aad9-45a1-aaf7-b0ee0e84b287%7D/), GitHub: [sloretz](https://github.com/sloretz)).**

----------------------------------------
Lots of info is stored on `ModelIdentifier`, but there is no unit test for this class. There should be one.

**Comment by chapulina** [comment]
There's a unit test now. Please reopen this if that's not enough.

https://github.com/ignitionrobotics/ign-fuel-tools/blob/master/src/ModelIdentifier_TEST.cc
