### ISSUE TITLE
[Fuel backend] Delete temp_fuel_client.cc and remove from CMakeLists.txt

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-fuel-tools#27]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-fuel-tools/issues/27)) by Shane Loretz (Bitbucket: [Shane Loretz](https://bitbucket.org/%7B656e3311-aad9-45a1-aaf7-b0ee0e84b287%7D/), GitHub: [sloretz](https://github.com/sloretz)).**

----------------------------------------
This file was a temporary one for testing the client before unit tests were written. It should be removed.

**Comment by chapulina** [comment]
I don't see it anymore
