### ISSUE TITLE
[Fuel backend] Some headers should or shouldn't be installed

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-fuel-tools#29]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-fuel-tools/issues/29)) by Shane Loretz (Bitbucket: [Shane Loretz](https://bitbucket.org/%7B656e3311-aad9-45a1-aaf7-b0ee0e84b287%7D/), GitHub: [sloretz](https://github.com/sloretz)).**

----------------------------------------
`LocalCache.hh` doesn't need to be installed, but it is. `Helpers` needs to be installed, but it isn't.

**Comment by chapulina** [comment]
`Helpers.hh` is already being installed, but `LocalCache.hh` could be removed here:

https://github.com/ignitionrobotics/ign-fuel-tools/blob/1676ab9986ee30f025a101a4d421c8f5cfde74f4/include/ignition/fuel_tools/CMakeLists.txt#L1-L4

Or, even better, it could be moved to the `src` folder.

**Comment by ahcorde** [comment]
PR is open https://github.com/ignitionrobotics/ign-fuel-tools/pull/109
