### ISSUE TITLE
[Girder backend] Remove "collection" REST endpoint

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-fuel-tools#3]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-fuel-tools/issues/3)) by Andrés Fortier (Bitbucket: [andres_fortier](https://bitbucket.org/%7Bf9c4496c-9146-4675-b1d5-bd0ed156cf58%7D/)).**

----------------------------------------
Since we will be uploading assets on each user collection we should remove the `collection` REST endpoint. This should be doable with a plugin.

**Comment by chapulina** [comment]
I believe we're not considering Girder any more, so closing this.
