### ISSUE TITLE
[Fuel backend] Setup CI Tests

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-fuel-tools#30]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-fuel-tools/issues/30)) by Ian Chen (Bitbucket: [Ian Chen](https://bitbucket.org/%7Beaa6fca5-6deb-43f6-907f-971c144735dd%7D/), GitHub: [iche033](https://github.com/iche033)).**

----------------------------------------
it's been tested primarily on ubuntu trusty and xenial

We should set up CI so we can test on osx and windows

**Comment by chapulina** [comment]
I think this can be closed, as @scpeters said we already have CI running for all platforms.
