### ISSUE TITLE
[Fuel backend] Add authentication

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-fuel-tools#33]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-fuel-tools/issues/33)) by Ian Chen (Bitbucket: [Ian Chen](https://bitbucket.org/%7Beaa6fca5-6deb-43f6-907f-971c144735dd%7D/), GitHub: [iche033](https://github.com/iche033)).**

----------------------------------------
to access secure routes on the backend, we need to add support for token based authentication with auth0

**Comment by chapulina** [comment]
This is now possible passing the JWT token on the header: `--header 'authorization: Bearer <JWT TOKEN>'`
