### ISSUE TITLE
[Girder frontend] Remove access to the "Collections" UI

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-fuel-tools#4]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-fuel-tools/issues/4)) by Andrés Fortier (Bitbucket: [andres_fortier](https://bitbucket.org/%7Bf9c4496c-9146-4675-b1d5-bd0ed156cf58%7D/)).**

----------------------------------------
Related to #3, we should remove the "Collections" entry in the web UI. I think this should be possible by overriding the view(s) in a plugin.

**Comment by chapulina** [comment]
I believe we're not considering Girder any more, so closing this.
