### ISSUE TITLE
Private headers shouldn't be installed

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-fuel-tools#44]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-fuel-tools/issues/44)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
We try to keep private headers in the `src` folder instead of `include` so they don't get installed.

**Comment by chapulina** [comment]
Related to #29

**Comment by ahcorde** [comment]
PR is open https://github.com/ignitionrobotics/ign-fuel-tools/pull/109
