### ISSUE TITLE
Cached models lose server and name information

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-fuel-tools#45]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-fuel-tools/issues/45)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
While working on issue #39, I realized that locally cached models lose some information which makes it harder to reuse them.

1. The first one is the **server** information, i.e. https://api.ignitionfuel.org.

1. The second one is the **model name**; while the whole web side is using names that may have capital letters and spaces, the local cache is converting to lower case and spaces into underscores.

This means that when a user requests a model from a URL, I can't check its `ModelIdentifier` (i.e. [UniqueName](https://ignitionrobotics.org/api/fuel_tools/1.0/classignition_1_1fuel__tools_1_1ModelIdentifier.html#a5555252ba4d85c2710ba3cf41d334f34)) against any model on the local cache.

I have a proposal which I'm not sure would be ok to roll into the released version 1:

Structure the local cache just like the server:
 
* add the server as a directory, maybe even with the version number
* use the model's human readable name

Current cache example:

~~~
/home/louise/.ignition/fuel/
├── config.yaml
└── models
    ├── caguero
    │   ├── ambulance3
    │   └── hammer
    ├── chapulina
    │   └── turtlebot
    └── german
        ├── bowl
        └── cardboard_box
~~~

Proposed cache example:
~~~
/home/louise/.ignition/fuel/
├── config.yaml
└── api.ignitionfuel.org
    └── 1.0
        ├── caguero
        │   └── models
        │       ├── Ambulance3
        │       └── Hammer
        ├── chapulina
        │   └── models
        │       └── Turtlebot
        └── german
            └── models
                ├── Bowl
                └── Cardboard Box
~~~
 
Other advantages:

* Models with same name and owner but different servers won't be overridden
* Models with names which currently map to same path won't be overridden (for example `chapulina/My Model` and `chapulina/my_model` can both exist on the server)
* Immediate association to a URL
* No need to track 2 separate names and keep making sure we're using the right ones all over the code

Disadvantages:

* Dealing with spaces in file paths, is this such a big issue?
* Is there anything else I'm missing?

**Comment by chapulina** [comment]
I believe the cache is already using the server URL and the upstream model name.
