### ISSUE TITLE
[Girder frontend] Add tags to UI

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-fuel-tools#5]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-fuel-tools/issues/5)) by Andrés Fortier (Bitbucket: [andres_fortier](https://bitbucket.org/%7Bf9c4496c-9146-4675-b1d5-bd0ed156cf58%7D/)).**

----------------------------------------
As a first approach, tags will be handled by using the metadata field. Once that is in place we should add our custom UI module to add / remove tags to an asset instead of editing the metadata "tags" field

**Comment by chapulina** [comment]
I believe we're not considering Girder any more, so closing this.
