### ISSUE TITLE
Move Ruby code to Python

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-fuel-tools#6]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-fuel-tools/issues/6)) by Andrés Fortier (Bitbucket: [andres_fortier](https://bitbucket.org/%7Bf9c4496c-9146-4675-b1d5-bd0ed156cf58%7D/)).**

----------------------------------------
Girder provides a client implemented in python (girder-cli) which already defines all the interactions with a Girder server. To avoid re-writing most of that we should migrate our ruby implementation of the commands to python, so it just becomes a thin wrapper around the existing libraries.

**Comment by chapulina** [comment]
I believe we're not considering Girder any more, so closing this.
