### ISSUE TITLE
Integrate ign-fuel-tools with Gazebo

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-fuel-tools#9]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-fuel-tools/issues/9)) by Andrés Fortier (Bitbucket: [andres_fortier](https://bitbucket.org/%7Bf9c4496c-9146-4675-b1d5-bd0ed156cf58%7D/)).**

----------------------------------------
Integrate gazebo with ignition fuel tools, so we can search and download models from the remote repository to the local machine running Gazebo. 

@caguero I'm leaving this issue here, but maybe in the future we'll want to migrate it to Gazebo's repo?

**Comment by chapulina** [comment]
I'll close this in favor of https://github.com/osrf/gazebo/issues/2406
